roboteq_ros2_driver:
  ros__parameters:
    pub_odom_tf: true
    odom_frame: "odom"
    base_frame: "base_link"
    cmdvel_topic: "cmd_vel"
    odom_topic: "odom"
    port: "/dev/ttyUSB0"
    baud: 230600
    open_loop: true
    wheel_circumference: 0.490088
    track_width: 0.6
    encoder_ppr: 4096
    encoder_cpr: 16384
    max_amps: 30.0
    max_rpm: 333.333
    gear_ratio: 9.0
